---
title: "All Functions with eelr2012 Dataset"
author: "Stuart Wagenius"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{All Functions with eelr2012 Dataset}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



# Introduction

This


Begin by loading the package

```{r}
library(mateable)
packageDescription("mateable")$Version
```

## Real dataset

```{r,fig.width=9, fig.height=6}
str(eelr2012)

# describe columns


# now we make a mating scene object

eelr <- makeScene(eelr2012, startCol = "firstDay", endCol = "lastDay",
                       xCol = "Ecoord", yCol = "Ncoord", idCol = "tagNo")

# summarize characteristics of mating scene
eSum <- matingSummary(eelr)

# look at metrics you are intersted in either by index
eSum[c("meanSD", "sdSD", "meanDur", "sdDur", "peak")]
eSum[c("minX", "minY", "k1")]

# or by name...
eSum$minX
eSum$minY
eSum$k1

# visualize
plotScene(eelr, "s")
plotScene(eelr, "s", pch = 1)

plotScene(eelr, "t")
plotScene(eelr, "t", sub = 'all', drawQuartiles = FALSE, text.cex = 0.5)
plotScene(eelr, c('s','t'), sub = 'random', N = 4, text.cex = 0.5)

plot3DScene(eelr)
plot3DScene(eelr, pt.cex = .5, sub = 'random', N = 4)

ePair <- pairDist(eelr) # matrix of distances between pairs
hist(ePair, 40)

eKnn <- kNearNeighbors(eelr, 6) # 6 nearest neighbors
hist(eKnn[, 3], 40)

eOver <- overlap(eelr, compareToSelf = T) # number of days overlapping
str(eOver)

eRecep <- receptivityByDay(eelr) # T/F receptive on each day
str(eRecep)
dailyReceptivitySummary <- receptivityByDay(eelr, summary = TRUE)
dailyReceptivitySummary # number of flowering individuals on each day; a vector named by date
plot(as.Date(names(dailyReceptivitySummary)), dailyReceptivitySummary, xlab = 'date', ylab = 'count of receptive individuals')

eProx <- proximity(eelr, "maxPropSqrd")
eProx$pop
hist(eProx$ind$proximity, 30)

eSync <- synchrony(eelr, "overlap")
eSync$pop

plotPotential(eProx)
plotPotential(eSync)

```


## Simulated dataset

```{r,fig.width=9, fig.height=6}
# make scene based off eelr summary information
simScene <- simulateScene(size = nrow(eelr), meanSD = eSum$meanSD,
                          sdSD = eSum$sdSD, meanDur = eSum$meanDur,
                          sdDur = eSum$sdDur, xRange = c(eSum$minX, eSum$maxX),
                          yRange = c(eSum$minY, eSum$maxY))

sProx <- proximity(simScene, "maxPropSqrd")
sSync <- synchrony(simScene, "augspurger")
sComp <- compatibility(simScene, "si_echinacea")

plotScene(simScene)
plot3DScene(simScene, sub = 'random')

plotPotential(sSync)
plotPotential(sProx)
plotPotential(sComp, density = FALSE)
plotPotential(sComp,plotType = c('net','heat'), density = FALSE)

plot3DPotential(list(sProx, sSync), subject = "ind")
plot3DPotential(list(sProx, sSync), subject = "ind", sample = 'all')
plot3DPotential(list(sProx, sSync), subject = "ind", sample = 'random')

plot3DPotential(list(sProx, sSync, sComp))
plot3DPotential(list(sProx, sSync, sComp), sub.ids = c(21,4))

```


## Multi-year scenes
```{r,fig.width=9, fig.height=7}
simScene1 <- simulateScene(size = nrow(eelr), meanSD = eSum$meanSD,
                          sdSD = eSum$sdSD, meanDur = eSum$meanDur,
                          sdDur = eSum$sdDur, xRange = c(eSum$minX, eSum$maxX),
                          yRange = c(eSum$minY, eSum$maxY))
simScene2<- simulateScene(size = nrow(eelr), meanSD = eSum$meanSD,
                          sdSD = eSum$sdSD, meanDur = eSum$meanDur,
                          sdDur = eSum$sdDur, xRange = c(eSum$minX, eSum$maxX),
                          yRange = c(eSum$minY, eSum$maxY))
simScene3 <- simulateScene(size = nrow(eelr), meanSD = eSum$meanSD,
                          sdSD = eSum$sdSD, meanDur = eSum$meanDur,
                          sdDur = eSum$sdDur, xRange = c(eSum$minX, eSum$maxX),
                          yRange = c(eSum$minY, eSum$maxY))

multiYearScene <- list('2012' = simScene1,'2013' = simScene2, '2014' = simScene3)

plotScene(multiYearScene)
plot3DScene(multiYearScene, pt.cex = 1.2)

syncMulti <- synchrony(multiYearScene, method = 'augs')
proxMulti <- proximity(multiYearScene, method = 'maxPropSqrd')
compatMulti <- compatibility(multiYearScene, method = 'si_echinacea')

plotPotential(syncMulti)
plotPotential(proxMulti)

plot3DPotential(list(syncMulti, proxMulti, compatMulti), subject = 'ind')

```


