// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// pair_sync_aug_noself
NumericMatrix pair_sync_aug_noself(NumericVector syncMatrix, NumericVector durMatrix, int n);
RcppExport SEXP mateable_pair_sync_aug_noself(SEXP syncMatrixSEXP, SEXP durMatrixSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type syncMatrix(syncMatrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type durMatrix(durMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(pair_sync_aug_noself(syncMatrix, durMatrix, n));
    return __result;
END_RCPP
}
// pair_sync_aug_self
NumericMatrix pair_sync_aug_self(NumericVector syncMatrix, NumericVector durMatrix, int n);
RcppExport SEXP mateable_pair_sync_aug_self(SEXP syncMatrixSEXP, SEXP durMatrixSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type syncMatrix(syncMatrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type durMatrix(durMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(pair_sync_aug_self(syncMatrix, durMatrix, n));
    return __result;
END_RCPP
}
// pair_sync_either_noself
NumericMatrix pair_sync_either_noself(NumericVector syncMatrix, int n);
RcppExport SEXP mateable_pair_sync_either_noself(SEXP syncMatrixSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type syncMatrix(syncMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(pair_sync_either_noself(syncMatrix, n));
    return __result;
END_RCPP
}
// pair_sync_either_self
NumericMatrix pair_sync_either_self(NumericVector syncMatrix, int n);
RcppExport SEXP mateable_pair_sync_either_self(SEXP syncMatrixSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type syncMatrix(syncMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(pair_sync_either_self(syncMatrix, n));
    return __result;
END_RCPP
}
// sync_loop_nodiag
IntegerVector sync_loop_nodiag(IntegerVector starts, IntegerVector ends, int n);
RcppExport SEXP mateable_sync_loop_nodiag(SEXP startsSEXP, SEXP endsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(sync_loop_nodiag(starts, ends, n));
    return __result;
END_RCPP
}
// sync_loop_diag
IntegerVector sync_loop_diag(IntegerVector starts, IntegerVector ends, int n);
RcppExport SEXP mateable_sync_loop_diag(SEXP startsSEXP, SEXP endsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(sync_loop_diag(starts, ends, n));
    return __result;
END_RCPP
}
// either_loop_nodiag
IntegerVector either_loop_nodiag(IntegerVector starts, IntegerVector ends, int n);
RcppExport SEXP mateable_either_loop_nodiag(SEXP startsSEXP, SEXP endsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(either_loop_nodiag(starts, ends, n));
    return __result;
END_RCPP
}
// either_loop_diag
IntegerVector either_loop_diag(IntegerVector starts, IntegerVector ends, int n);
RcppExport SEXP mateable_either_loop_diag(SEXP startsSEXP, SEXP endsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ends(endsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(either_loop_diag(starts, ends, n));
    return __result;
END_RCPP
}
