# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sync_loop_nodiag <- function(starts, ends, n) {
    .Call('mateable_sync_loop_nodiag', PACKAGE = 'mateable', starts, ends, n)
}

sync_loop_diag <- function(starts, ends, n) {
    .Call('mateable_sync_loop_diag', PACKAGE = 'mateable', starts, ends, n)
}

either_loop_nodiag <- function(starts, ends, n) {
    .Call('mateable_either_loop_nodiag', PACKAGE = 'mateable', starts, ends, n)
}

either_loop_diag <- function(starts, ends, n) {
    .Call('mateable_either_loop_diag', PACKAGE = 'mateable', starts, ends, n)
}

