# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pair_sync_aug_noself <- function(syncMatrix, durMatrix, n) {
    .Call('mateable_pair_sync_aug_noself', PACKAGE = 'mateable', syncMatrix, durMatrix, n)
}

pair_sync_aug_self <- function(syncMatrix, durMatrix, n) {
    .Call('mateable_pair_sync_aug_self', PACKAGE = 'mateable', syncMatrix, durMatrix, n)
}

pair_sync_either_noself <- function(syncMatrix, n) {
    .Call('mateable_pair_sync_either_noself', PACKAGE = 'mateable', syncMatrix, n)
}

pair_sync_either_self <- function(syncMatrix, n) {
    .Call('mateable_pair_sync_either_self', PACKAGE = 'mateable', syncMatrix, n)
}

daysSync_noself <- function(starts, ends, n) {
    .Call('mateable_daysSync_noself', PACKAGE = 'mateable', starts, ends, n)
}

daysSync_self <- function(starts, ends, n) {
    .Call('mateable_daysSync_self', PACKAGE = 'mateable', starts, ends, n)
}

daysEither_noself <- function(starts, ends, n) {
    .Call('mateable_daysEither_noself', PACKAGE = 'mateable', starts, ends, n)
}

daysEither_self <- function(starts, ends, n) {
    .Call('mateable_daysEither_self', PACKAGE = 'mateable', starts, ends, n)
}

