# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pair_si_ech <- function(s1, s2) {
    .Call('mateable_pair_si_ech', PACKAGE = 'mateable', s1, s2)
}

pair_dioecious <- function(s1, s2) {
    .Call('mateable_pair_dioecious', PACKAGE = 'mateable', s1, s2)
}

daysSync_noself <- function(starts, ends, n) {
    .Call('mateable_daysSync_noself', PACKAGE = 'mateable', starts, ends, n)
}

daysSync_self <- function(starts, ends, n) {
    .Call('mateable_daysSync_self', PACKAGE = 'mateable', starts, ends, n)
}

daysEither_noself <- function(starts, ends, n) {
    .Call('mateable_daysEither_noself', PACKAGE = 'mateable', starts, ends, n)
}

daysEither_self <- function(starts, ends, n) {
    .Call('mateable_daysEither_self', PACKAGE = 'mateable', starts, ends, n)
}

